import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'testing - Dra Tuane Cássia',
	description: 'Generated by create next app',
};

export default function Home() {
	return (
		<>
			<h1>Main page!</h1>
		</>
	);
}
